### ISSUE TITLE
The function name in the ngx.log is incorrect

### ISSUE THREAD

**Issue by rainingmaster** [openresty/lua-nginx-module#1179] opened 2017-10-30 06:39 UTC
First of all, I think the default template output in `ngx.log` should be: `the filename: the number of rows: the function name`, and I don't know if my understanding is correct?

I assume that this is correct, and I find that when a module calls a function of another, if we add `return` like [here](https://github.com/rainingmaster/lua-nginx-module/commit/984e1931cd3f8164f4a6215c59238ee11e317d93#diff-cdaccee15afe07bfa2bceadb7a2d83eeR568), it will cause the function name to be wrong when using `ngx.log`.

This is what I think is normal: the output is the correct function name mylog defined [here](https://github.com/rainingmaster/lua-nginx-module/commit/984e1931cd3f8164f4a6215c59238ee11e317d93#diff-cdaccee15afe07bfa2bceadb7a2d83eeR625), and if you call the function with the `return` like above, the [output is the caller's function name `bar` instead of `mylog`](https://github.com/rainingmaster/lua-nginx-module/commit/984e1931cd3f8164f4a6215c59238ee11e317d93#diff-cdaccee15afe07bfa2bceadb7a2d83eeR585).
 At this point, the description becomes: `the filename: the number of rows: the calling function name`. Is this inappropriate?

I found that log information was acquired using `lua_getinfo` during read the source code. Is this a luajit problem?

And this is my branch for list the different: https://github.com/openresty/lua-nginx-module/compare/master...rainingmaster:log_tag

**Comment by tokers** [comment] 2017-10-30 08:27
Someone also came up with a similar problem in
 https://www.freelists.org/post/luajit/setfenv-with-tail-calls .
And Mike gave his answer.

**Comment by spacewander** [comment] 2017-10-30 12:27
@rainingmaster 
You are not the first one hit this problem...
See the post in luajit mail list: https://www.freelists.org/post/luajit/Bad-stack-trace-from-lua-getstack-and-lua-getinfo
It is because the tail call will be optimized in LuaJIT.

**Comment by agentzh** [comment] 2017-10-30 18:12
Right, it's really about tail-call optimizations in LuaJIT. Just avoid the tail-call syntax when you want proper Lua backtrace. Not a bug at all but a feature :) I'm closing this.

**Closed by agentzh** 2017-10-30 18:12 UTC

**Comment by rainingmaster** [comment] 2017-10-31 02:06
Thank you all, I know it. we can use `return (func(1, 2, 3))` to avoid this problem.
