### ISSUE TITLE
doc: confused ngx.worker.id() maybe return meaningful values should by only for NGINX 1.9.7+

### ISSUE THREAD

**Issue by monkeyzhu123** [openresty/lua-nginx-module#1404] opened 2018-10-30 09:45 UTC
This function returns meaningful values only for NGINX 1.9.1+. With earlier versions of NGINX, it always returns nil.

See also ngx.worker.count.

This API was first introduced in the 0.9.20 release.

BUT Lua Nginx Module to 0.9.20 first used in openresty 1.9.7.1

In my openresty/1.9.3.1 ngx.worker.id() return nill

**Comment by agentzh** [comment] 2018-10-30 20:01
@monkeyzhu123 Will you give us a minimal and standalone example that we can easily run and reproduce the problem you are seeing on our side? Thanks!

**Comment by monkeyzhu123** [comment] 2018-10-31 02:29
ok~,
my openresty nginx -V output  openresty/1.9.3.1 and ngx_lua 0.9.16 

`init_worker_by_lua_file /opt/openresty/nginx/conf/test_ngx_work_id.lua;`
xand `test_ngx_work_id.lua`

    if 0 == ngx.worker.id() then
        ngx.log(ngx.ERR, "work_id is: ", 0)
    else
        ngx.log(ngx.ERR, "work_id is: ", ngx.worker.id())
    end

errorlog output

    2018/10/31 10:17:57 [error] 7831#0: init_worker_by_lua_file error: /opt/openresty/nginx/conf/test_ngx_work_id.lua:1: attempt to call field 'id' (a nil value)
    stack traceback:
            /opt/openresty/nginx/conf/test_ngx_work_id.lua:1: in main chunk
    2018/10/31 10:17:57 [error] 7833#0: init_worker_by_lua_file error: /opt/openresty/nginx/conf/test_ngx_work_id.lua:1: attempt to call field 'id' (a nil value)
    stack traceback:
            /opt/openresty/nginx/conf/test_ngx_work_id.lua:1: in main chunk
    2018/10/31 10:17:57 [error] 7834#0: init_worker_by_lua_file error: /opt/openresty/nginx/conf/test_ngx_work_id.lua:1: attempt to call field 'id' (a nil value)
    stack traceback:
            /opt/openresty/nginx/conf/test_ngx_work_id.lua:1: in main chunk
    2018/10/31 10:17:57 [error] 7832#0: init_worker_by_lua_file error: /opt/openresty/nginx/conf/test_ngx_work_id.lua:1: attempt to call field 'id' (a nil value)
    stack traceback:
            /opt/openresty/nginx/conf/test_ngx_work_id.lua:1: in main chunk
    2018/10/31 10:17:57 [error] 7835#0: init_worker_by_lua_file error: /opt/openresty/nginx/conf/test_ngx_work_id.lua:1: attempt to call field 'id' (a nil value)
    stack traceback:
            /opt/openresty/nginx/conf/test_ngx_work_id.lua:1: in main chunk

and for this ,i try to use openresty 1.9.x lastest release 1.9.15.1,it use /ngx_lua-0.10.5,same lua code 
output

2018/10/31 10:27:03 [error] 3908#0: [lua] test_ngx_work_id.lua:2: work_id is: 0, context: init_worker_by_lua*
    2018/10/31 10:27:03 [error] 3910#0: [lua] test_ngx_work_id.lua:4: work_id is: 2, context: init_worker_by_lua*
    2018/10/31 10:27:03 [error] 3912#0: [lua] test_ngx_work_id.lua:4: work_id is: 4, context: init_worker_by_lua*
    2018/10/31 10:27:03 [error] 3911#0: [lua] test_ngx_work_id.lua:4: work_id is: 3, context: init_worker_by_lua*
    2018/10/31 10:27:03 [error] 3909#0: [lua] test_ngx_work_id.lua:4: work_id is: 1, context: init_worker_by_lua*

**Comment by agentzh** [comment] 2018-10-31 04:50
@monkeyzhu123 Will you please try the latest openresty version? We're not interested in debugging an old version since it might already be fixed in newer ones.

**Comment by agentzh** [comment] 2018-10-31 04:51
@monkeyzhu123 BTW, the coding style `if 0 == ngx.worker.id() then` does not make much sense in Lua since Lua's assignment expressions cannot be used on the expression level anyway...

**Comment by agentzh** [comment] 2018-10-31 04:55
@monkeyzhu123 I just tried your example give above with OpenResty 1.13.6.2 and I'm getting the expected error log messages:

```
2018/10/30 21:54:38 [notice] 109874#109874: signal process started
2018/10/30 21:54:38 [error] 109875#109875: *2 [lua] init_worker_by_lua:3: work_id is: 0, context: init_worker_by_lua*
2018/10/30 21:54:38 [error] 109877#109877: *3 [lua] init_worker_by_lua:5: work_id is: 2, context: init_worker_by_lua*
2018/10/30 21:54:38 [error] 109876#109876: *4 [lua] init_worker_by_lua:5: work_id is: 1, context: init_worker_by_lua*
2018/10/30 21:54:38 [error] 109878#109878: *5 [lua] init_worker_by_lua:5: work_id is: 3, context: init_worker_by_lua*
```

**Comment by agentzh** [comment] 2018-10-31 04:57
OpenResty 1.9.x were released more than 2 years ago...in 2016...

**Comment by agentzh** [comment] 2018-10-31 04:58
Oh sorry, you were actually using OpenResty 1.9.3.1, which was released on 12 August 2015. More than 3 years ago...

**Comment by monkeyzhu123** [comment] 2018-11-01 04:06
Yes, I started using it very early，and the lastest openresty no error for ngx.worker.id().   I can  also use the way of upgrading openresty version.  for this  issue ，the document description for `ngx.worker.id()` earliest   openresty version  is  not 1.9.1+.  It should be 1.9.7+.   There is a mistake for document。 

Finally ，Thank you for your contribution to the community.

**Comment by agentzh** [comment] 2018-11-02 00:29
@monkeyzhu123 Well, early versions do have that feature, just buggy I think. So the docs are not wrong anyway ;)

**Closed** 2018-11-02 00:29 UTC
