### ISSUE TITLE
Disabling Object Revalidation using LUA

### ISSUE THREAD

**Issue by davidsnt** [openresty/lua-nginx-module#508] opened 2015-05-07 05:39 UTC
This is not really an issue but a question,

I am trying to disable object revalidation at my caching layer based on query args, tried the following code 

if ngx.var.args ~= nil then
  match,err = ngx.re.match(ngx.var.args, "myqueryarg")
  if match then
     ngx.req.clear_header("If-Modified-Since")
     ngx.req.clear_header("If-None-Match")
  end
end

Though the headers are set to nil, I still see the server responding 304. Any help is appreciated.

**Comment by agentzh** [comment] 2015-05-07 07:15
@davidsnt I cannot reason about the cause with so little information provided, sorry. Several suggestions:

1. ensure that ngx.req.clear_header() code path is indeed executed by adding logging statements to that path.
2. ensure your ngx.req.clear_header() calls run *before* any header filters (like in an early request processing phase like "access" or "rewrite"). Because the 304 response is generated by a standard nginx header filter module.

Failing all above, try provide a minimal and standalone example with detailed steps that can help reproduce the issue on my side.

BTW, general questions should go to the openresty-en mailing list. Please see http://openresty.org/#Community Thanks for your cooperation :)

**Comment by davidsnt** [comment] 2015-05-07 15:24
Thank you for the suggestion, I am moving this topic to https://groups.google.com/forum/#!topic/openresty-en/8FLTtAICDEY. BTW, I tried both access_by_lua directive and rewrite_by_lua and on the logs I can see the filters are working as expected example log lines, but still I see a 304 on the client side.

*1 [lua] clear_header.lua:1: Inside Lua error: Success[0]
*1 [lua] clear_header.lua:5: Inside match error: Success[0]
*1 [lua] clear_header.lua:6: Tue, 14 Apr 2015 03:33:44 GMT error: Success[0]
*1 [lua] clear_header.lua:7: "cd98cadaf838b6d3a33d5d58cffcbb6f" error: Success[0]
*1 [lua] clear_header.lua:12: nil error: Success[0]
*1 [lua] clear_header.lua:13: nil error: Success[0]

----------------
Lua with logging, sample location block,

location /my-home/{
            access_by_lua '
ngx.log(ngx.ERR, "Inside Lua")
if ngx.var.args ~= nil then
  match,err = ngx.re.match(ngx.var.args, "query_args")
  if match then
     ngx.log(ngx.ERR, "Inside match")
     ngx.log(ngx.ERR, ngx.req.get_headers()["If-Modified-Since"])
     ngx.log(ngx.ERR, ngx.req.get_headers()["If-None-Match"])
     ngx.req.clear_header("If-Modified-Since")
     ngx.req.clear_header("If-None-Match")
     ngx.log(ngx.ERR, ngx.req.get_headers()["If-Modified-Since"])
     ngx.log(ngx.ERR, ngx.req.get_headers()["If-None-Match"])
  end
end
';
        }

**Comment by agentzh** [comment] 2015-05-08 03:49
This discussion has been moved to the openresty-en mailing list. Let's avoid cross-posting. I'm closing this ticket.

**Closed by agentzh** 2015-05-08 03:49 UTC
