### ISSUE TITLE
Compilation fails because OpenSSL 1.1 is not supported

### ISSUE THREAD

**Issue by alex-mashin** [openresty/lua-nginx-module#1172] opened 2017-10-21 08:58 UTC
While trying to build openresty-1.11.2.5 under Ubuntu 17.10, a compilation error happens:
```
src/event/ngx_event_openssl.c: In function ‘ngx_ssl_connection_error’:
src/event/ngx_event_openssl.c:2048:21: error: ‘SSL_R_NO_CIPHERS_PASSED’ undeclared (first use in this function); did you mean ‘SSL_R_NO_CIPHERS_SPECIFIED’?
             || n == SSL_R_NO_CIPHERS_PASSED                          /*  182 */
                     ^~~~~~~~~~~~~~~~~~~~~~~
                     SSL_R_NO_CIPHERS_SPECIFIED
```

Did you mean `SSL_R_NO_CIPHERS_SPECIFIED`?

**Comment by spacewander** [comment] 2017-10-21 15:39
Maybe the problem is the same with #903. What openssl version do you use under Ubuntu 17.10?

**Comment by alex-mashin** [comment] 2017-10-21 15:52
OpenSSL 1.1.0f  25 May 2017

**Comment by spacewander** [comment] 2017-10-21 16:18
@alex-mashin 
OpenSSL 1.1 is not supported yet. You could use OpenSSL 1.0.2 instead, or install OpenResty via official package: http://openresty.org/en/linux-packages.html#ubuntu

**Comment by spacewander** [comment] 2017-10-21 17:08
@alex-mashin 
Seems you are not lucky enough to use the official package...
You could download OpenSSL 1.0.2 and use `./configure --with-openssl=/path/to/lib/the_openssl_version(for example, openssl-1.0.2h)` to compile OpenResty, instead of changing system-wide OpenSSL.

**Comment by spacewander** [comment] 2017-10-21 17:15
Sorry for missing two things:
1. You need to apply patch before compiling the OpenSSL.
2. You need to compile the OpenSSL to get the library file before running `./configure --with-openssl=...`.

See the [.travis.yml](https://github.com/openresty/lua-nginx-module/blob/master/.travis.yml#L113).

**Comment by agentzh** [comment] 2017-10-22 18:18
@alex-mashin Seems like there is something already listening on the 80 port? Please stop those daemons and retry installing the openresty binary package. This is because installing openresty will start the daemon automatically.

**Comment by agentzh** [comment] 2017-10-22 18:19
@alex-mashin Or better, tune your system to avoid starting the service immediately after installing a deb package in general: https://major.io/2014/06/26/install-debian-packages-without-starting-daemons/

**Comment by agentzh** [comment] 2017-10-22 18:20
@spacewander We want the community to use binary packages instead of going through the lengthy and error-prone compilation process :)

**Comment by alex-mashin** [comment] 2017-10-24 12:43
Nothing is listening on the port 80 and installing the package will not help: nginx will not launch anyway.

**Comment by agentzh** [comment] 2017-10-26 04:52
@alex-mashin Well, the official pre-built package requires the Intel SSE 4.2 instruction set, which makes a big performance difference in special cases.

**Comment by bencooling** [comment] 2017-11-01 07:12
I get the same error on fresh install of Ubuntu 16.04 on Rackspace, following the [prebuilt linux package instructions](http://openresty.org/en/linux-packages.html) for Ubuntu.  This is the result of the `uname -a` command:

```bash
$ uname -a
Linux pry 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Am I right in assuming the Rackspace 16.04 Ubuntu image is not one of the supported amd64 or i386 architectures?

**Comment by agentzh** [comment] 2017-11-01 20:54
@bencooling The thing you want to check is the SSE 4.2 instruction set support in your CPU model.

**Comment by theraw** [comment] 2018-01-01 20:36
i'm also having a error which i think is because i'm using OpenSSL 1.1.0
```bash
		/opt/nginx/modules/lua-nginx-module/src/ngx_http_lua_ssl_ocsp.c
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-unused-local-typedefs -Wno-error -DNDK_SET_VAR -DNDK_UPSTREAM_LIST -DNDK_SET_VAR -I/opt/nginx/modules/nginx-mtask-module -I/usr/include/mysql -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /opt/nginx/modules/ngx_devel_kit/objs -I objs/addon/ndk -I /opt/nginx/modules/lua-nginx-module/src/api -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I /opt/nginx/modules/ngx_devel_kit/src -I /opt/nginx/modules/ngx_devel_kit/src -I /opt/nginx/modules/ngx_devel_kit/objs -I objs/addon/ndk -I /opt/nginx/modules/ngx_pagespeed-1.13.35.1-beta/psol/include -I /opt/nginx/modules/ngx_pagespeed-1.13.35.1-beta/psol/include/third_party/chromium/src -I /opt/nginx/modules/ngx_pagespeed-1.13.35.1-beta/psol/include/third_party/google-sparsehash/src/src -I /opt/nginx/modules/ngx_pagespeed-1.13.35.1-beta/psol/include/third_party/google-sparsehash/gen/arch/linux/x64/include -I /opt/nginx/modules/ngx_pagespeed-1.13.35.1-beta/psol/include/third_party/grpc/src/include -I /opt/nginx/modules/ngx_pagespeed-1.13.35.1-beta/psol/include/third_party/protobuf/src/src -I /opt/nginx/modules/ngx_pagespeed-1.13.35.1-beta/psol/include/third_party/re2/src -I /opt/nginx/modules/ngx_pagespeed-1.13.35.1-beta/psol/include/out/Release/obj/gen -I /opt/nginx/modules/ngx_pagespeed-1.13.35.1-beta/psol/include/out/Release/obj/gen/protoc_out/instaweb -I /opt/nginx/modules/ngx_pagespeed-1.13.35.1-beta/psol/include/third_party/apr/src/include -I /opt/nginx/modules/ngx_pagespeed-1.13.35.1-beta/psol/include/third_party/aprutil/src/include -I /opt/nginx/modules/ngx_pagespeed-1.13.35.1-beta/psol/include/third_party/apr/gen/arch/linux/x64/include -I /opt/nginx/modules/ngx_pagespeed-1.13.35.1-beta/psol/include/third_party/aprutil/gen/arch/linux/x64/include -I /opt/nginx/modules/ngx_pagespeed-1.13.35.1-beta/psol/include/url -I /usr/local/include/luajit-2.0 -I /usr/local/modsecurity/include -I src/stream \
		-o objs/addon/src/ngx_http_lua_lex.o \
		/opt/nginx/modules/lua-nginx-module/src/ngx_http_lua_lex.c
/opt/nginx/modules/lua-nginx-module/src/ngx_http_lua_ssl_ocsp.c: In function ‘ngx_http_lua_ffi_ssl_set_ocsp_status_resp’:
/opt/nginx/modules/lua-nginx-module/src/ngx_http_lua_ssl_ocsp.c:471:17: error: dereferencing pointer to incomplete type
     if (ssl_conn->tlsext_status_type == -1) {
                 ^
make[1]: *** [objs/addon/src/ngx_http_lua_ssl_ocsp.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/opt/nginx/sources/nginx-1.13.8'
make: *** [build] Error 2
```
tried with OpenSSL 1.0.2h everything went well
```bash
	objs/ngx_modules.o \
	-Wl,-rpath,/usr/local/lib/ -Wl,-E -ldl -lpthread -lpthread -lcrypt /opt/nginx/modules/ngx_pagespeed-1.13.35.1-beta/psol/lib/Release/linux/x64/pagespeed_automatic.a -lstdc++ -lrt -pthread -lm -luuid -lmaxminddb -lmaxminddb -L/usr/local/lib -lluajit-5.1 -lm -ldl -L/usr/lib/x86_64-linux-gnu -lmariadbclient -Wl,-rpath,/usr/local/modsecurity/lib -L/usr/local/modsecurity/lib -lmodsecurity -lpcre /opt/nginx/openssl-OpenSSL_1_0_2h//.openssl/lib/libssl.a /opt/nginx/openssl-OpenSSL_1_0_2h//.openssl/lib/libcrypto.a -ldl -lz -lxml2 -lxslt -lexslt -lgd -lGeoIP \
	-Wl,-E
make[1]: Leaving directory `/opt/nginx/sources/nginx-1.13.8'
```

**Comment by agentzh** [comment] 2018-01-03 00:35
Closing it as it is duplicate with #903, for example.

The official support for OpenSSL 1.1.0 is underway (as in #1213 and openresty/openresty#324).

**Closed by agentzh** 2018-01-03 00:36 UTC

**Comment by yzrds** [comment] 2018-07-23 10:50
I solved the program, another situation, you may not close the nginx
