### ISSUE TITLE
empty $upstream_connect_time, $upstream_header_time and $upstream_response_time

### ISSUE THREAD

**Issue by niroshanaj** [openresty/lua-nginx-module#1246] opened 2018-01-30 05:54 UTC
Hello,

VER_NGINX_DEVEL_KIT=0.3.0
VER_LUA_NGINX_MODULE=0.10.10
VER_NGINX=1.12.0
VER_LUAJIT=2.0.5

I'm having an issue with nignx access logs. I'm not able to get $upstream_connect_time, $upstream_header_time and $upstream_response_time in my access logs. This happens only when I use "ngx.location.capture" within content_by_lua_block.

Section of my nginx.conf
`
http {
  log_format upstream_time '$remote_addr - $remote_user [$time_local] '
                               '"$request" $status $body_bytes_sent '
                               '"$http_referer" "$http_user_agent"'
                               'rt=$request_time uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time"';
  server {
      server_name sb-nginx-lua-server;
      listen 1987;
      access_log /var/log/nginx/access.log upstream_time;
      error_log /var/log/nginx/error.log warn;

      
      location = /test {
          lua_need_request_body on;
          content_by_lua_block {
             local res = ngx.location.capture("/sub", { method = ngx.HTTP_POST, always_forward_body = true })
             local json = require "cjson"
             local xml = require "xml"
             local data = xml.load(res.body)
             local jsonData = json.encode(data)
             ngx.say(jsonData)
           }
        }

      location = /sub {
        proxy_pass http://test.com;
        proxy_read_timeout 30s;

        proxy_set_header          X-Real-IP       $remote_addr;
        proxy_set_header          X-Forwarded-For $proxy_add_x_forwarded_for;
      }
    }
}

`
access logs for curl http://localhost:1987/test

`
172.22.0.2 - - [30/Jan/2018:05:25:17 +0000] "GET /test HTTP/1.1" 200 14 "-" "curl/7.55.0"rt=0.013 uct="-" uht="-" urt="-"
172.22.0.2 - - [30/Jan/2018:05:25:19 +0000] "GET /test HTTP/1.1" 200 14 "-" "curl/7.55.0"rt=0.021 uct="-" uht="-" urt="-"
172.22.0.2 - - [30/Jan/2018:05:25:19 +0000] "GET /test HTTP/1.1" 200 14 "-" "curl/7.55.0"rt=0.027 uct="-" uht="-" urt="-"
172.22.0.2 - - [30/Jan/2018:05:25:20 +0000] "GET /test HTTP/1.1" 200 14 "-" "curl/7.55.0"rt=0.016 uct="-" uht="-" urt="-"
172.22.0.2 - - [30/Jan/2018:05:25:21 +0000] "GET /test HTTP/1.1" 200 14 "-" "curl/7.55.0"rt=0.027 uct="-" uht="-" urt="-"
`

access logs for curl http://localhost:1987/sub

`
172.22.0.2 - - [30/Jan/2018:05:24:29 +0000] "GET /sub HTTP/1.1" 200 334 "-" "curl/7.55.0"rt=0.015 uct="0.002" uht="0.015" urt="0.015"
172.22.0.2 - - [30/Jan/2018:05:25:10 +0000] "GET /sub HTTP/1.1" 200 346 "-" "curl/7.55.0"rt=0.042 uct="0.001" uht="0.042" urt="0.042"
172.22.0.2 - - [30/Jan/2018:05:25:11 +0000] "GET /sub HTTP/1.1" 200 346 "-" "curl/7.55.0"rt=0.014 uct="0.002" uht="0.014" urt="0.014"
172.22.0.2 - - [30/Jan/2018:05:25:12 +0000] "GET /sub HTTP/1.1" 200 334 "-" "curl/7.55.0"rt=0.020 uct="0.001" uht="0.020" urt="0.020"
172.22.0.2 - - [30/Jan/2018:05:25:13 +0000] "GET /sub HTTP/1.1" 200 346 "-" "curl/7.55.0"rt=0.019 uct="0.003" uht="0.018" urt="0.019"
172.22.0.2 - - [30/Jan/2018:05:25:13 +0000] "GET /sub HTTP/1.1" 200 334 "-" "curl/7.55.0"rt=0.126 uct="0.035" uht="0.126" urt="0.126"
`
can you please let me know if I'm doing anything wrong or suggestions get it working

**Comment by qlees** [comment] 2018-01-30 09:36
Without communication with upstream server, How can you get the upstream_connect_time?

**Comment by niroshanaj** [comment] 2018-01-30 09:55
@qlees did I miss anything ?

**Comment by tokers** [comment] 2018-01-30 10:40
@niroshanaj This is an expected result since this kind of variables(`http_name`, `sent_http_name`, `arg_name`, `cookie_name` and `upstream_http_name`) always call the `get_handler`. `share_all_vars` makes sense for cacheable variables.

**Comment by niroshanaj** [comment] 2018-01-30 11:08
@tokers Thanks for your explanation. "share_all_vars" and "copy_all_vars" was added while I was debugging and not meant to be there.
With regards to missing variables, do you have any suggestions, workaround ?. 
I'm debugging some performance issues and I thinks having  $upstream_response_time will give me some insights it the problem.
Thanks

**Comment by spacewander** [comment] 2018-01-30 12:39
@niroshanaj 
There is actually two requests in your issue. One is the main request, the other one is the sub request.
It is the sub request which connects to the upstream, but it is the main request which logs the access log.
Therefore, you could not find the `$upstream_xxx` variables in the main request's access log, as the main request doesn't connect to the upstream at all.

The `$upstream_xxx` variables are calculated from the upstream request result on the fly. So using `shared_all_vars` doesn't fix the problem, as the main request and sub request share the storage of variables, but not the upstream request result.

There is a way to work around it. You could enable the subrequest access logging via specifying `log_subrequest on` in your nginx.conf.

**Comment by niroshanaj** [comment] 2018-01-31 04:09
@spacewander Thanks for your suggestions. I have managed to get it working with setting
`log_subrequest on` 
and adding logging at sub level.
Thanks again for your support

**Comment by spacewander** [comment] 2018-01-31 04:30
@niroshanaj 
Consider closing this issue?

**Comment by niroshanaj** [comment] 2018-02-01 06:11
@spacewander, I have another issue (which is not related to my original post),
I'm getting ` worker process XX exited on signal 11` error on error.log every time when  
`(110: Connection timed out) while connecting to upstream` or `(111: Connection refused) while connecting to upstream` error occurs

Any idea why this is happening,  any suggestions would be highly appreciated

**Comment by spacewander** [comment] 2018-02-01 06:25
@niroshanaj 
Bad news. Signal 11 means SigSegv. It is time to renew your C debug skill and start to investigate the core dump. It is also important to make the segmentfault easy to reproduce and read the debug log.

Since the original issue is resolved, I suggest you to close this one.

If you think the core dump is related with OpenResty, please open another issue and provide a minimal reproduce case, so that we could reproduce it.

Good luck.

**Comment by agentzh** [comment] 2018-02-02 23:18
Consider it resolved.

**Comment by agentzh** [comment] 2018-02-02 23:19
@niroshanaj You should try out the latest version of OpenResty bundle to avoid running into known issues.

**Closed by agentzh** 2018-02-02 23:18 UTC
