### ISSUE TITLE
lua goes wrong when copy and run openresty in path different from configure --prefix

### ISSUE THREAD

**Issue by isaacdong** [openresty/lua-nginx-module#784] opened 2016-05-31 13:38 UTC
**backgroud:**

i am building a  openresty example(contains openresty, configs and demo bash scripts). wish everyone in my team is able to check out and run it in any path. then, i get this error...

openresty versoin 1.9.7.4  and i notice an option in nginx -V `-rpath,/walle/openresty/luajit/lib`
**steps:**
./configure --prefix=/walle/openresty ...  make ; make install
rename /walle/openresty to /walle/foobar
copy it into /Users/isaac/swap/openresty for test.

**command line output as following:**

> $ pwd
> /Users/isaac/swap/openresty/nginx/Users/isaac/swap/openresty/nginx
> 
> $ ./sbin/nginx -p /Users/isaac/swap/openresty/nginx -V
> dyld: Library not loaded: /walle/openresty/luajit/lib/libluajit-5.1.2.dylib
>   Referenced from: /Users/isaac/swap/openresty/nginx/./sbin/nginx
>   Reason: image not found
> Trace/BPT trap: 5
>

**Comment by agentzh** [comment] 2016-05-31 18:11
@isaacdong No, the installation tree of OpenResty is not relocatable by design, as you can see from the runtime error messages. The `nginx` executable of OpenResty relies on the location specified (by `--prefix=PATH` of `./configure`) when building OpenResty to find dynamic libraries it depends on. Similarly, OpenResty relies on the same prefix to locate the default Lua libraries shipped by OpenResty.

Very few C/C++ projects in the *NIX world allows moving the installation trees to a different location than specified at build time.

**Comment by agentzh** [comment] 2016-05-31 18:14
@isaacdong For team work, you can share the same OpenResty installation tree for the whole team but each team member specifies a different server prefix (to a directory under her own home directory, for example) while invoking the same `nginx` binary, as demonstrated below:

https://openresty.org/en/getting-started.html

This way you can also avoid messing up with the OpenResty installation tree when developing multiple OpenResty-based projects. And it's easier to upgrade OpenResty for the whole team in the future.

**Comment by isaacdong** [comment] 2016-06-01 04:48
Thanks for your patience! got your point. 
howerver, in my case, i get 3  openresty, each of them is built with a different experimental module.
so i add a update my demo scripts: has to manually  confirm installation of  openresty in the right place, to run it.

**Comment by agentzh** [comment] 2016-06-01 06:01
OpenResty's install too tree is not and will not be relocatable. I am closing this.

**Closed by agentzh** 2016-06-01 06:01 UTC
