### ISSUE TITLE
Is there is a way don't let set_uri_args escape argument?

### ISSUE THREAD

**Issue by enson69** [openresty/lua-nginx-module#1091] opened 2017-06-15 09:27 UTC
I found the  ngx.set_uri_args  would escape argument keys and values. 
Is there is a way don't let set_uri_args escape argument?
======================================
ngx.req.set_uri_args
a Lua table holding the query arguments' key-value pairs, as in
  ngx.req.set_uri_args({ a = 3, b = "hello world" })
where in the latter case, this method will escape argument keys and values according to the URI escaping rule.

**Comment by agentzh** [comment] 2017-06-15 15:59
@enson69 That is by design. If you want to set escaped querystring directly, just assign to the nginx standard variable `$args`, as in

```lua
ngx.var.args = "foo=hello%20world&bar=5"
```

**Closed by agentzh** 2017-06-15 15:59 UTC
